[General]
#enter your call here
Homecall=mycall

#enter your coordinates for your default position in dd.mmm
#for southern logitude, and western latitude enter a -
HomeLat=50.848
HomeLong=5.688

#viewing range for google earth in km. Valid values are
#200 for regional level, 50 for city level, 5 for street level
Range=200

#your qrz login details. leave the password blank if you want as it isn't stored encrypted
#then the program will ask you the password every time you start the program
QRZUser=myqrz
QRZPass=

#the default udp-port for N1mm is 12060. leave it on 0 and the program will set it automatically
UDPport=12060

#set the location for the "networked" kml-file for google earth
#when empty, the file will be created in the program directory
"windowsformat "c:\kmlfile"
KMLfile=
